apiVersion: v1
kind: Service
metadata:
  name: saas-backend
  namespace: saas
spec:
  type: ClusterIP
  selector:
    app: saas-backend
  ports:
    - port: 4000
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-backend
  namespace: saas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saas-backend
  template:
    metadata:
      labels:
        app: saas-backend
      annotations:
        secrets-store.csi.k8s.io/used-by: "saas-backend"
        secrets-store.csi.k8s.io/sync-secret: "true"   # <-- this forces sync to K8s Secret
    spec:
      serviceAccountName: saas-backend-sa
      containers:
      - name: saas-backend
        image: 784074784226.dkr.ecr.ap-south-1.amazonaws.com/saas-backend:latest
        ports:
          - containerPort: 4000
        envFrom:
          - secretRef:
              name: db-secret         # <-- this will be created automatically
          - configMapRef:
              name: saas-config
        volumeMounts:
          - name: secrets-store
            mountPath: /mnt/secrets-store
            readOnly: true
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: saas-rds-spc