apiVersion: v1
kind: Service
metadata:
  name: saas-frontend
  namespace: saas
spec:
  type: LoadBalancer
  selector:
    app: saas-frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-frontend
  namespace: saas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saas-frontend
  template:
    metadata:
      labels:
        app: saas-frontend
    spec:
      containers:
        - name: saas-frontend
          image: 784074784226.dkr.ecr.ap-south-1.amazonaws.com/saas-frontend:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: saas-config
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
