apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: saas-rds-spc
  namespace: saas
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "saas-rds-credentials"   # your AWS Secrets Manager name
        objectType: "secretsmanager"
  secretObjects:
    - secretName: db-secret                  # Kubernetes secret to create
      type: Opaque
      data:
        - objectName: username
          key: username
        - objectName: password
          key: password
        - objectName: host
          key: host
        - objectName: dbname
          key: dbname

