apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: saas-rds-spc
  namespace: saas
spec:
  provider: aws
  parameters:
    # objects is a YAML list in string form
    objects: |
      - objectName: "saas-rds-credentials"        # Secrets Manager secret name (or ARN)
        objectType: "secretsmanager"       # or "ssm" for Parameter Store
  secretObjects:                           # OPTIONAL: sync to Kubernetes Secret (requires syncSecret.enabled=true)
    - secretName: db-secret                # this K8s Secret will be created/updated
      type: Opaque
      data:
        - objectName: username
          key: DB_USER
        - objectName: password
          key: DB_PASSWORD
        - objectName: host
          key: DB_HOST
        - objectName: port
          key: DB_PORT
        - objectName: dbname
          key: DB_NAME
