apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: saas-rds-spc
  namespace: saas
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "saas-rds-credentials"
        objectType: "secretsmanager"
  secretObjects:
    - secretName: db-secret
      type: Opaque
      data:
        - objectName: saas-rds-credentials
          key: username
        - objectName: saas-rds-credentials
          key: password
        - objectName: saas-rds-credentials
          key: host
        - objectName: saas-rds-credentials
          key: dbname
